@echo off
echo Creating directories...
mkdir "3do" 2>nul
mkdir "64dd" 2>nul
mkdir "amiga1200" 2>nul
mkdir "amiga600" 2>nul
mkdir "amigacd32" 2>nul
mkdir "amigacdtv" 2>nul
mkdir "amstradcpc" 2>nul
mkdir "apple2" 2>nul
mkdir "apple2gs" 2>nul
mkdir "arduboy" 2>nul
mkdir "atari2600" 2>nul
mkdir "atari5200" 2>nul
mkdir "atari7800" 2>nul
mkdir "atari800" 2>nul
mkdir "atarist" 2>nul
mkdir "atomiswave" 2>nul
mkdir "bbcmicro" 2>nul
mkdir "bk" 2>nul
mkdir "c64" 2>nul
mkdir "cdi" 2>nul
mkdir "channelf" 2>nul
mkdir "colecovision" 2>nul
mkdir "daphne" 2>nul
mkdir "dos" 2>nul
mkdir "dragon" 2>nul
mkdir "dreamcast" 2>nul
mkdir "easyrpg" 2>nul
mkdir "fbneo" 2>nul
mkdir "fds" 2>nul
mkdir "gamegear" 2>nul
mkdir "gb" 2>nul
mkdir "gba" 2>nul
mkdir "gbc" 2>nul
mkdir "gw" 2>nul
mkdir "gx4000" 2>nul
mkdir "intellivision" 2>nul
mkdir "jaguar" 2>nul
mkdir "lowresnx" 2>nul
mkdir "lutro" 2>nul
mkdir "lynx" 2>nul
mkdir "macintosh" 2>nul
mkdir "mame" 2>nul
mkdir "mame-advmame" 2>nul
mkdir "mame-libretro" 2>nul
mkdir "mame-mame4all" 2>nul
mkdir "mastersystem" 2>nul
mkdir "megadrive" 2>nul
mkdir "megaduck" 2>nul
mkdir "moonlight" 2>nul
mkdir "msx" 2>nul
mkdir "msx1" 2>nul
mkdir "msx2" 2>nul
mkdir "msxturbor" 2>nul
mkdir "multivision" 2>nul
mkdir "n64" 2>nul
mkdir "naomi" 2>nul
mkdir "naomigd" 2>nul
mkdir "neogeo" 2>nul
mkdir "neogeocd" 2>nul
mkdir "nes" 2>nul
mkdir "ngp" 2>nul
mkdir "ngpc" 2>nul
mkdir "o2em" 2>nul
mkdir "openbor" 2>nul
mkdir "oricatmos" 2>nul
mkdir "palm" 2>nul
mkdir "pc" 2>nul
mkdir "pc88" 2>nul
mkdir "pc98" 2>nul
mkdir "pcengine" 2>nul
mkdir "pcenginecd" 2>nul
mkdir "pcfx" 2>nul
mkdir "pcv2" 2>nul
mkdir "pico" 2>nul
mkdir "pico8" 2>nul
mkdir "pokemini" 2>nul
mkdir "ports" 2>nul
mkdir "psp" 2>nul
mkdir "psx" 2>nul
mkdir "roms" 2>nul
mkdir "samcoupe" 2>nul
mkdir "satellaview" 2>nul
mkdir "saturn" 2>nul
mkdir "scummvm" 2>nul
mkdir "scv" 2>nul
mkdir "sega32x" 2>nul
mkdir "segacd" 2>nul
mkdir "sg1000" 2>nul
mkdir "snes" 2>nul
mkdir "solarus" 2>nul
mkdir "spectravideo" 2>nul
mkdir "sufami" 2>nul
mkdir "supergrafx" 2>nul
mkdir "supervision" 2>nul
mkdir "thomson" 2>nul
mkdir "ti994a" 2>nul
mkdir "tic80" 2>nul
mkdir "trs80coco" 2>nul
mkdir "uzebox" 2>nul
mkdir "vectrex" 2>nul
mkdir "vg5000" 2>nul
mkdir "vic20" 2>nul
mkdir "videopacplus" 2>nul
mkdir "virtualboy" 2>nul
mkdir "wasm4" 2>nul
mkdir "wswan" 2>nul
mkdir "wswanc" 2>nul
mkdir "x1" 2>nul
mkdir "x68000" 2>nul
mkdir "zmachine" 2>nul
mkdir "zx81" 2>nul
mkdir "zxspectrum" 2>nul

echo Starting downloads...
for /F "usebackq tokens=*" %%A in ("downloads.txt") do (
    echo Processing: %%A
    %%A
)
echo Download complete!
pause
